// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtpsSwr4pCahsENPaEKflLaCdQqlh_pco',
    appId: '1:1007762784529:web:3c6eab2ba67443c6f2ccb0',
    messagingSenderId: '1007762784529',
    projectId: 'hospital-app-aditya',
    authDomain: 'hospital-app-aditya.firebaseapp.com',
    storageBucket: 'hospital-app-aditya.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDszbXA4Z-CS8eo6wkWAyDbSi4kgdjE5Lk',
    appId: '1:1007762784529:android:1eac1f82e6291044f2ccb0',
    messagingSenderId: '1007762784529',
    projectId: 'hospital-app-aditya',
    storageBucket: 'hospital-app-aditya.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbm63NvJmHMii9WTHNYr4Zp7dUBOiCtzk',
    appId: '1:1007762784529:ios:32f4ffcafb03ecfcf2ccb0',
    messagingSenderId: '1007762784529',
    projectId: 'hospital-app-aditya',
    storageBucket: 'hospital-app-aditya.firebasestorage.app',
    iosBundleId: 'com.example.hostpital2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbm63NvJmHMii9WTHNYr4Zp7dUBOiCtzk',
    appId: '1:1007762784529:ios:32f4ffcafb03ecfcf2ccb0',
    messagingSenderId: '1007762784529',
    projectId: 'hospital-app-aditya',
    storageBucket: 'hospital-app-aditya.firebasestorage.app',
    iosBundleId: 'com.example.hostpital2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtpsSwr4pCahsENPaEKflLaCdQqlh_pco',
    appId: '1:1007762784529:web:721101c257d862c0f2ccb0',
    messagingSenderId: '1007762784529',
    projectId: 'hospital-app-aditya',
    authDomain: 'hospital-app-aditya.firebaseapp.com',
    storageBucket: 'hospital-app-aditya.firebasestorage.app',
  );
}
